apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:mirecloud/home_lab.git"
    targetRevision: HEAD
    # On pointe vers le dossier de CONFIGURATION
    path: infrastructure/external-secrets-config
  destination:
    server: https://kubernetes.default.svc
    # Peu importe le namespace pour un ClusterSecretStore, mais on reste groupé
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
