apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
spec:
  project: default
  source:
    repoURL: git@github.com:TON_ORG/TON_REPO.git
    targetRevision: main
    path: loki-stack-custom
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
