# templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include ".Release.Name" . }}-storage-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  # AJOUTE CETTE LIGNE :
  storageClassName: "nfs-client" 
  resources:
    requests:
      storage: {{ .Values.extraInit.pvcStorage }}