{{- range .Values.servingEngineSpec.modelSpec }}
{{- if .pvcStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Use $.Release.Name to access the root scope inside the loop
  # Use .name to access the current item in the iteration
  name: {{ $.Release.Name }}-{{ .name }}-pvc
  labels:
    app: vllm
    model: {{ .name }}
spec:
  accessModes:
    - {{ .pvcStorage.accessMode }}
  resources:
    requests:
      storage: {{ .pvcStorage.size }}
  storageClassName: {{ .pvcStorage.storageClassName }}
---
{{- end }}
{{- end }}