apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "secure-loki-access"
  namespace: monitoring
spec:
  #  CIBLE : On verrouille tout ce qui s'appelle 'loki'
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki

  ingress:
    #  RÈGLE : Seuls les voisins du namespace 'monitoring' peuvent entrer.
    # (Cela autorise Grafana et Promtail qui sont dans le même namespace)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "3100" # Port du Backend
              protocol: TCP
            - port: "80" # Port de la Gateway
              protocol: TCP
