# -----------------------------------------------------------------------------
# Configuration Cilium Home Lab (v1.19.3)
# -----------------------------------------------------------------------------

# 1. Cœur du système (eBPF & Network)
kubeProxyReplacement: "true"
k8sServiceHost: "192.168.2.75"
k8sServicePort: 6443

# 2. Remplacement de MetalLB (L2 Announcements)
l2announcements:
  enabled: true

# Autorise les IPs externes pour les services LoadBalancer
externalIPs:
  enabled: true

enableNodePort: true
enableHostServices: true

# 3. Observabilité (Hubble & Logs)
hubble:
  enabled: true

  # Le Relay permet à la CLI et à l'UI de voir les flux
  relay:
    enabled: true

  # L'interface Web Hubble
  ui:
    enabled: true
    replicas: 1

  # ACTIVATION DU FLOW EXPORTER
  # C'est ce bloc qui crée le pod qui envoie les logs vers stdout
  flowExporter:
    enabled: true

  # Export des logs vers stdout (format JSON pour Loki/Promtail)
  export:
    static:
      enabled: true
      format: json
      filePath: "/dev/stdout"

# 4. Ingress Controller & Gateway API
gatewayAPI:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared

# 5. Optimisations Lab
operator:
  replicas: 1

debug:
  enabled: false
