apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mirecloud-ca-es
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mirecloud-ca-key-pair # Le nom du secret final qui sera créé
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls   # Important pour que ce soit un secret TLS valide
  data:
  - secretKey: tls.crt
    remoteRef:
      key: mirecloud/ca
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: mirecloud/ca
      property: tls.key