apiVersion: v2
name: nginx-wrapper
description: Wrapper chart pour Nginx  MireCloud
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: nginx 
    version: 2.2.0
    repository: oci://registry-1.docker.io/cloudpirates
