{
 "title": "Cilium Flows - Hubble Observer",
 "description": "Grafana dashboard for Cilium Flows - Hubble Observer",
 "tags": [
  "cilium",
  "network",
  "hubble"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "sourcenamespace",
    "label": "Source Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "destinationnamespace",
    "label": "Destination Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   { "name": "direction", "label": "Direction", "query": "INGRESS, EGRESS" },
   { "name": "ipversion", "label": "IP Version", "query": "IPv4, IPv6" },
   { "name": "searchregex", "label": "Search Regex" },
   { "name": "excluderegex", "label": "Exclude Regex", "query": "a^" },
   { "name": "hubbleobservernamespace", "query": "monitoring" },
   {
    "name": "logparser",
    "query": "regexp `(?P<message>.+)` | line_format `{{.message}}` | json"
   },
   { "name": "hubbleobservercf2cnpurl", "query": "https://cf2cnp.local" }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Flows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        | json \n        | line_format \"{{.flow}}\" \n        | json flow_source_namespace=\"source.namespace\", flow_destination_namespace=\"destination.namespace\", flow_traffic_direction=\"traffic_direction\", flow_verdict=\"verdict\", flow_IP_ipVersion=\"IP.ipVersion\"\n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\"\n        [$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Flows per Verdict",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(flow_verdict) (\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        |~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n        | json flow_verdict=\"flow.verdict\", flow_source_namespace=\"flow.source.namespace\", flow_destination_namespace=\"flow.destination.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\"\n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\" \n        | flow_IP_ipVersion=~\"$ipversion\"\n    [$__range])\n)",
     "legendFormat": "{{flow_verdict}}"
    }
   ]
  },
  {
   "title": "Flows per Direction",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(flow_traffic_direction) (\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        |~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n        | json flow_traffic_direction=\"flow.traffic_direction\", flow_source_namespace=\"flow.source.namespace\", flow_destination_namespace=\"flow.destination.namespace\", flow_IP_ipVersion=\"flow.IP.ipVersion\"\n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\" \n        | flow_IP_ipVersion=~\"$ipversion\"\n    [$__range])\n)"
    }
   ]
  },
  {
   "title": "Flows per Source Namespace",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(flow_source_namespace) (\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        |~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n        | json flow_source_namespace=\"flow.source.namespace\", flow_destination_namespace=\"flow.destination.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\"\n        | flow_source_namespace!=\"\" \n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\" \n        | flow_IP_ipVersion=~\"$ipversion\"\n    [$__range])\n)"
    }
   ]
  },
  {
   "title": "Flows per Destination",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(flow_destination_name) (\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        |~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n        | json flow_dns=\"flow.destination_names[0]\", flow_pod=\"flow.destination.pod_name\", flow_source_namespace=\"flow.source.namespace\", flow_destination_namespace=\"flow.destination.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\"\n        | label_format flow_destination_name=\"{{ if .flow_dns }}{{ .flow_dns }}{{ else }}{{ .flow_pod }}{{ end }}\"\n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\" \n        | flow_IP_ipVersion=~\"$ipversion\" \n        | flow_destination_name!=\"\"\n    [$__range])\n)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Flows per Verdict (per $__interval)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(flow_verdict) (\n    count_over_time(\n        {namespace=\"monitoring\", app=\"hubble-logger\"} \n        |~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n        | json flow_verdict=\"flow.verdict\", flow_source_namespace=\"flow.source.namespace\", flow_destination_namespace=\"flow.destination.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\"\n        | flow_source_namespace=~\"$sourcenamespace\" \n        | flow_destination_namespace=~\"$destinationnamespace\" \n        | flow_traffic_direction=~\"$direction\" \n        | flow_IP_ipVersion=~\"$ipversion\"\n    [$__auto])\n)",
     "legendFormat": "{{flow_verdict}}"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Cilium Flows over Time",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"monitoring\", app=\"hubble-logger\"} \n|~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n| json flow_verdict=\"flow.verdict\", flow_IP_source=\"flow.IP.source\", flow_source_pod_name=\"flow.source.pod_name\", flow_source_namespace=\"flow.source.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\", flow_l4_TCP_destination_port=\"flow.l4.TCP.destination_port\", flow_l4_UDP_destination_port=\"flow.l4.UDP.destination_port\", flow_l4_ICMPv4_type=\"flow.l4.ICMPv4.type\", flow_destination_pod_name=\"flow.destination.pod_name\", flow_destination_name=\"flow.destination_names[0]\", flow_destination_namespace=\"flow.destination.namespace\", flow_IP_destination=\"flow.IP.destination\", flow_drop_reason_desc=\"flow.drop_reason_desc\", flow_uuid=\"flow.uuid\", flow_source_labels=\"flow.source.labels\", flow_destination_labels=\"flow.destination.labels\"\n| flow_source_namespace=~\"$sourcenamespace\" | flow_destination_namespace=~\"$destinationnamespace\" | flow_traffic_direction=~\"$direction\" | flow_IP_ipVersion=~\"$ipversion\"\n| label_format \n    Verdict=`{{.flow_verdict}}`,\n    Source_IP=`{{.flow_IP_source}}`,\n    Source=`{{ if .flow_source_pod_name }}{{.flow_source_pod_name}} (Pod) {{else}} {{.flow_source_labels}} (Label) {{end}}`,\n    Source_Namespace=`{{.flow_source_namespace}}`,\n    Direction=`{{.flow_traffic_direction}}`,\n    Dest_Port=`{{ if .flow_l4_TCP_destination_port}}TCP-{{.flow_l4_TCP_destination_port}}{{else if .flow_l4_UDP_destination_port}}UDP-{{.flow_l4_UDP_destination_port}}{{else if .flow_l4_ICMPv4_type}} ICMPv4 {{else}}-{{end}}`,\n    Destination=`{{ if .flow_destination_pod_name }}{{.flow_destination_pod_name}} (Pod) {{ else if .flow_destination_name }}{{.flow_destination_name}} (URL){{else}} {{.flow_destination_labels}} (Label) {{end}}`,\n    Destination_Namespace=`{{.flow_destination_namespace}}`,\n    Destination_IP=`{{.flow_IP_destination}}`, \n    Drop_Description=`{{.flow_drop_reason_desc}}`,\n    Flow_UUID=`{{.flow_uuid}}`",
     "maxLines": 100
    }
   ]
  },
  { "title": "Unique Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Unique Cilium Flows",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"monitoring\", app=\"hubble-logger\"} \n|~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n| json flow_verdict=\"flow.verdict\", flow_IP_source=\"flow.IP.source\", flow_source_pod_name=\"flow.source.pod_name\", flow_source_namespace=\"flow.source.namespace\", flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\", flow_l4_TCP_destination_port=\"flow.l4.TCP.destination_port\", flow_l4_UDP_destination_port=\"flow.l4.UDP.destination_port\", flow_l4_ICMPv4_type=\"flow.l4.ICMPv4.type\", flow_destination_pod_name=\"flow.destination.pod_name\", flow_destination_name=\"flow.destination_names[0]\", flow_destination_namespace=\"flow.destination.namespace\", flow_IP_destination=\"flow.IP.destination\", flow_drop_reason_desc=\"flow.drop_reason_desc\", flow_uuid=\"flow.uuid\", flow_source_labels=\"flow.source.labels\", flow_destination_labels=\"flow.destination.labels\"\n| flow_source_namespace=~\"$sourcenamespace\" | flow_destination_namespace=~\"$destinationnamespace\" | flow_traffic_direction=~\"$direction\" | flow_IP_ipVersion=~\"$ipversion\"\n| label_format \n    Verdict=`{{.flow_verdict}}`,\n    Source_IP=`{{.flow_IP_source}}`,\n    Source=`{{ if .flow_source_pod_name }}{{.flow_source_pod_name}} (Pod) {{else}} {{.flow_source_labels}} (Label) {{end}}`,\n    Source_Namespace=`{{.flow_source_namespace}}`,\n    Direction=`{{.flow_traffic_direction}}`,\n    Dest_Port=`{{ if .flow_l4_TCP_destination_port}}TCP-{{.flow_l4_TCP_destination_port}}{{else if .flow_l4_UDP_destination_port}}UDP-{{.flow_l4_UDP_destination_port}}{{else if .flow_l4_ICMPv4_type}} ICMPv4 {{else}}-{{end}}`,\n    Destination=`{{ if .flow_destination_pod_name }}{{.flow_destination_pod_name}} (Pod) {{ else if .flow_destination_name }}{{.flow_destination_name}} (URL){{else}} {{.flow_destination_labels}} (Label) {{end}}`,\n    Destination_Namespace=`{{.flow_destination_namespace}}`,\n    Destination_IP=`{{.flow_IP_destination}}`, \n    Drop_Description=`{{.flow_drop_reason_desc}}`,\n    Flow_UUID=`{{.flow_uuid}}`",
     "maxLines": 100
    }
   ]
  },
  { "title": "Raw Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "logs",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"monitoring\", app=\"hubble-logger\"} \n|~ `(?i)$searchregex` !~ `(?i)$excluderegex`\n| json flow_traffic_direction=\"flow.traffic_direction\", flow_IP_ipVersion=\"flow.IP.ipVersion\", flow_destination_name=\"flow.destination_names[0]\"\n| flow_traffic_direction=~\"$direction\" \n| flow_IP_ipVersion=~\"$ipversion\""
    }
   ]
  }
 ]
}