apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-bind-secret
  namespace: external-dns # <--- REMPLACE kube-system PAR external-dns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rfc2136-tsig-secret
    creationPolicy: Owner
  data:
    - secretKey: tsig-secret
      remoteRef:
        key: secret/dns/rfc2136
        property: tsig-secret
