n8n:
  externalPostgresql:
    host: "postgres.postgres.svc"
    port: 5432
    database: "n8n"
    username: "postgres"
    existingSecret: "n8n-db-creds"
    existingSecretPasswordKey: "password"

  main:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteMany
      size: 5Gi
      # mountPath retiré

    extraEnvVars:
      N8N_HOST: "n8n.mirecloud.com"
      N8N_PORT: "5678"
      N8N_PROTOCOL: "https"
      WEBHOOK_URL: "https://n8n.mirecloud.com/"
      GENERIC_TIMEZONE: "America/Toronto"
      N8N_SECURE_COOKIE: "false"
      # N8N_ENCRYPTION_KEY → migrer vers existingSecret

  worker:
    mode: queue
    count: 2
    concurrency: 20

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: true
      existingSecret: "n8n-redis-creds"      # ← depuis Vault
      existingSecretPasswordKey: "password"

  ingress:
    enabled: true
    className: "cilium-ingress-controller"
    annotations:
      cert-manager.io/cluster-issuer: "mirecloud-ca-issuer"
    hosts:
      - host: n8n.mirecloud.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: n8n-tls-cert
        hosts:
          - n8n.mirecloud.com