apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-oidc
  namespace: openwebui
  labels:
    app: openwebui
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: openwebui-oidc
    creationPolicy: Owner

  data:
    - secretKey: client-secret
      remoteRef:
        key: secret/openwebui/secret
        property: client-secret

    - secretKey: webui-secret-key
      remoteRef:
        key: secret/openwebui/secret
        property: webui-secret-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mirecloud-ca-sync
  namespace: openwebui
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: mirecloud-ca-cert
    creationPolicy: Owner

  data:
    - secretKey: ca.crt
      remoteRef:
        key: secret/mirecloud/ca
        property: tls.crt