apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-oidc
  namespace: openwebui
  labels:
    app: openwebui 
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-oidc
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      #  IDEM ICI, CHEMIN SIMPLE
      key: secret/openweui/secret
      property: client-secret
   
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mirecloud-ca-sync
  namespace: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # C'est le nom du secret Kubernetes qui sera créé
    name: mirecloud-ca-cert 
    creationPolicy: Owner
  data:
  - secretKey: ca.crt
    remoteRef:
      key: secret/mirecloud/ca
      property: tls.crt