apiVersion: v2
name: keycloak-wrapper
description: Wrapper chart for Keycloak
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: keycloakx
    # On reprend la source que tu utilisais manuellement
    repository: "oci://ghcr.io/codecentric/helm-charts"
    version: "7.2.0" # Version stable récente, ajuste si tu en visais une précise
