apiVersion: v1
kind: Secret
metadata:
  name: byo-db-creds
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  password: "7lsoGvNqCuoqxVLxqL0hC0yL3WzQGQ26"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
type: Opaque
stringData:
  password: "admin"
