apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-backend"     # <--- C'est ICI que tu avais "argocd-role"
          serviceAccountRef:
            name: "ext-secrets-external-secrets" # Le compte exact que tu as trouvé tout à l'heure
            namespace: "external-secrets"