apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    # On demande à ArgoCD d'attendre un peu que les CRDs soient là
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-backend"
          serviceAccountRef:
            # ATTENTION : Avec le wrapper, vérifie bien que ce nom est correct une fois déployé.
            # Si tu as une erreur d'auth, c'est souvent le nom ici qui a changé (ex: external-secrets-wrapper-...)
            name: "ext-secrets-external-secrets" 
            namespace: "external-secrets"