apiVersion: v2
name: external-secrets-stack
description: Wrapper pour External Secrets Operator v1.2.0
type: application
version: 1.0.0
dependencies:
  - name: external-secrets
    version: 1.2.0 # La version exacte que tu as fournie
    repository: https://charts.external-secrets.io
