fullnameOverride: external-secrets

installCRDs: true

webhook:
  enabled: true
  certManager:
    enabled: true
    issuerRef:
      name: mirecloud-ca-issuer
      kind: ClusterIssuer

certController:
  create: false
