apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # C'est LA ligne qui corrige l'erreur de ta première capture d'écran
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      # On tape sur le Service "Active" pour tomber sur le Leader (vault-0 actuellement)
      server: "http://vault-active.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-backend"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"