apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    # Vague 5 : On s'assure que l'opérateur est installé (Vague 0) avant de créer ça
    argocd.argoproj.io/sync-wave: "5"
    # L'ANTIDOTE : Permet à ArgoCD d'appliquer le fichier même si la CRD n'est pas encore prête
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      # Adresse du Service HA de Vault (Mode Prod)
      server: "http://vault-active.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-backend"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"