apiVersion: v2
name: gitlab-wrapper
description: Wrapper pour déployer GitLab via ArgoCD
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: gitlab
    version: 9.7.0
    repository: https://charts.gitlab.io/
