# 1. DÉSACTIVER L'INSTALLATION DU CERT-MANAGER INCLUS (Le Fix du conflit)
certmanager:
  install: false

# 2. CONFIGURATION GLOBALE
global:
  hosts:
    domain: mirecloud.com
    gitlab:
      name: gitlab.mirecloud.com

  ingress:
    enabled: true
    configureCertmanager: false # On gère nous-mêmes via l'annotation ci-dessous
    provider: nginx
    class: nginx # Parfois nécessaire selon la version du chart
    annotations:
      kubernetes.io/ingress.class: nginx
      # C'est ici qu'on branche ton Cert-Manager existant
      cert-manager.io/cluster-issuer: mirecloud-ca-issuer
    tls:
      enabled: true
      secretName: gitlab-tls-auto

  # Désactive l'utilisation de cert-manager interne (redondance, mais bonne pratique)
  certmanager:
    enabled: false

# 3. RESTE DE TA CONFIG
gitlab-runner:
  install: false

postgresql:
  install: false

psql:
  host: postgres.postgres.svc.cluster.local
  port: 5432
  username: postgres
  database: gitlab
  password:
    secret: gitlab-postgres-secret
    key: password
