gitlab:
  # --- DÉSACTIVATION TOTALE DES VÉRIFICATIONS ---
  upgradeCheck:
    enabled: false   # Désactive le check de version DB
  
  global:
    common:
      check: false   # Désactive les checks de configuration généraux (souvent ignoré mais vital ici)
  # ---------------------------------------------

  global:
    edition: ce
    hosts:
      domain: mirecloud.com
      https: true
    
    ingress:
      configureCertmanager: false
      class: nginx
      annotations:
        cert-manager.io/cluster-issuer: "mirecloud-ca-issuer"
        nginx.ingress.kubernetes.io/proxy-body-size: "512m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      tls:
        enabled: true
        secretName: gitlab-tls

    # Ta configuration Postgres Externe
    psql:
      password:
        useSecret: true
        secret: gitlab-postgresql-password
        key: postgres-password
      host: postgres.postgres.svc
      port: 5432
      username: gitlab
      database: gitlab

    minio:
      enabled: true
    
    # Redis interne (simplifié pour éviter les erreurs de schéma)
    redis:
      host: ""

  # On s'assure que les migrations tournent pour peupler ta DB vide
  migrations:
    enabled: true

  # Désactivation des composants internes
  postgresql:
    install: false
  
  certmanager:
    install: false

  gitlab-runner:
    install: true
    rbac:
      create: true