gitlab:
  # --------------------------------------------------------
  # 1. DÉSACTIVATION DES VÉRIFICATIONS
  # --------------------------------------------------------
  upgradeCheck:
    enabled: false

  global:
    common:
      check: false

    edition: ce
    hosts:
      domain: mirecloud.com
      https: true

    # --------------------------------------------------------
    # 2. CONFIGURATION SSO (KEYCLOAK) - NOUVEAU !
    # --------------------------------------------------------
    appConfig:
      omniauth:
        enabled: true
        # Lie automatiquement le compte si l'email est identique
        autoLinkUser: ["openid_connect"]
        # Force le SSO pour ce provider
        allowSingleSignOn: ["openid_connect"]
        # false = Crée automatiquement l'utilisateur au premier login
        blockAutoCreatedUsers: false

        # Pointe vers le secret créé par ExternalSecret
        providers:
          - secret: gitlab-oidc-config
            key: provider

    # --------------------------------------------------------
    # 3. CONFIGURATION RESEAU & SSL
    # --------------------------------------------------------
    ingress:
      configureCertmanager: false
      class: nginx
      annotations:
        cert-manager.io/cluster-issuer: "mirecloud-ca-issuer"
        nginx.ingress.kubernetes.io/proxy-body-size: "512m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
      tls:
        enabled: true
        secretName: gitlab-tls

    # --------------------------------------------------------
    # 4. BASE DE DONNÉES EXTERNE
    # --------------------------------------------------------
    psql:
      password:
        useSecret: true
        secret: gitlab-postgresql-password
        key: postgres-password
      host: postgres.postgres.svc
      port: 5432
      # Important : On utilise l'utilisateur 'gitlab' (celui du secret Vault)
      username: postgres
      database: gitlab

    # Minio Interne
    minio:
      enabled: true

    # Redis Interne
    redis:
      host: ""

  # --------------------------------------------------------
  # 5. COMPOSANTS
  # --------------------------------------------------------
  migrations:
    enabled: true

  postgresql:
    install: false

  gitlab-runner:
    install: false # Désactivé comme convenu (sera sur VM)
