pgadmin4:
  env:
    # ATTENTION : J'ai vu "info@mirecloud.com" dans tes logs.
    # Assure-toi d'utiliser le même email pour te connecter !
    email: "info@mirecloud.com"
    contextPath: ""

  # --- CONFIGURATION SECRETE NATIVE ---
  # Au lieu de 'extraEnv', on dit au chart : "Le secret existe déjà, utilise-le."
  existingSecret: "pgadmin-admin-password"

  # On mappe les clés attendues par PgAdmin vers les clés de ton secret Vault
  secretKeys:
    pgadmin-password: "password"
    # (Si tu avais mis l'email dans Vault, on le mapperait ici aussi)
  # ------------------------------------

  # On supprime (ou laisse vide) extraEnv pour ne pas créer de doublons
  extraEnv: []

  # Ingress désactivé au profit de Gateway API (à configurer séparément via HTTPRoute)
  ingress:
    enabled: false
    # ingressClassName: nginx
    # annotations:
    #   cert-manager.io/cluster-issuer: "mirecloud-ca-issuer"
    #   nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # hosts:
    #   - host: pgadmin.mirecloud.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    # tls:
    #   - secretName: pgadmin-tls
    #     hosts:
    #       - pgadmin.mirecloud.com

  persistentVolume:
    enabled: true
    size: 5Gi
