pgadmin4:
  env:
  email: "admin@mirecloud.com" # Ton email de login
  existingSecret: "pgadmin-admin-password" # <-- Le nom défini dans ton ExternalSecret
  secretKeys:
    password: "password" # <-- La clé définie dans ton ExternalSecret
  service:
    type: ClusterIP # On change LoadBalancer -> ClusterIP car on utilise l'Ingress
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "mirecloud-ca-issuer"
    hosts:
      - host: pgadmin.mirecloud.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: pgadmin-tls-auto
        hosts:
          - pgadmin.mirecloud.com
