mlflow:
  backendStore:
    # 1. Configuration Postgres
    postgres:
      enabled: true
      host: "postgres.postgres.svc"
      port: 5432
      database: "mlflow"
      # On laisse user/password vides car gérés par le secret ci-dessous

    # 2.
    existingDatabaseSecret:
      name: "postgres-database-secret"
      usernameKey: "usernameKey"
      passwordKey: "passwordKey"

    # 3. Activation de la migration automatique (recommandé par la doc)
    databaseMigration: true

  # Authentification (Reste inchangé, c'était bon)
  auth:
    enabled: true
    existingAdminSecret:
      name: "mlflow-admin-credentials"
      usernameKey: "usernameKey"
      passwordKey: "passwordKey"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: mirecloud-ca-issuer
    hosts:
      - host: mlflow.mirecloud.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: mlflow-tls
        hosts:
          - mlflow.mirecloud.com

  gunicornOpts: ""
  extraArgs:
    allowedHosts: "*"
