mlflow:
  backendStore:
    postgres:
      enabled: true
      host: "postgresql.postgresql.svc" # Vérifie que ce DNS est correct dans ton cluster
      port: 5432
      database: "mlflow"

  existingDatabaseSecret:
    name: "postgres-database-secret"
    usernameKey: "username"
    passwordKey: "password"

  auth:
    enabled: true
    existingAdminSecret:
      name: "mlflow-admin-credentials"
      usernameKey: "username"
      passwordKey: "password"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: mirecloud-ca-issuer
    hosts:
      - host: mlflow.mirecloud.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: mlflow-tls
        hosts:
          - mlflow.mirecloud.com
