helm:
  valuesObject: # <--- UTILISE valuesObject PLUTÔT QUE values
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: rfc2136-tsig-secret
            key: tsig-secret
    rfc2136:
      host: "192.168.2.74"
      port: 53
      zone: "mirecloud.com"
      tsigKeyname: "externaldns-key"
      tsigAxfr: true
    sources:
      - service
      - ingress
      - gateway-httproute
    domainFilters:
      - mirecloud.com
    extraArgs:
      - --gateway-label-filter=gateway.networking.k8s.io/gateway-name=mirecloud-gateway
    policy: sync
