external-dns:
  provider:
    name: rfc2136

  env:
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      valueFrom:
        secretKeyRef:
          name: rfc2136-tsig-secret
          key: tsig-secret

  extraArgs:
    - --rfc2136-host=192.168.2.74
    - --rfc2136-port=53
    - --rfc2136-zone=mirecloud.com
    - --rfc2136-tsig-keyname=externaldns-key
    - --rfc2136-tsig-axfr
    - --gateway-label-filter=gateway.networking.k8s.io/gateway-name=mirecloud-gateway

  sources:
    - service
    - ingress
    - gateway-httproute

  domainFilters:
    - mirecloud.com

  policy: sync
