apiVersion: v1
kind: Pod
metadata:
  name: security-tester
  namespace: test-secret
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "sleep 10000"]
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-test-secret"