apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-es
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      #  ON NE MET PAS /data/ ICI.
      # L'opérateur le sait déjà.
      key: secret/keycloak/admin
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-es
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: byo-db-creds
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      #  IDEM ICI, CHEMIN SIMPLE
      key: secret/keycloak/db
      property: password