apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-es
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: byo-db-creds      # Nom correct pour le values.yaml
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      # ⚠️ CORRECTION ICI : Ajout de /data/ entre "secret" et "keycloak"
      key: secret/data/keycloak/db
      property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-es
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-password # Nom correct pour le values.yaml
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      # ⚠️ CORRECTION ICI : Ajout de /data/
      key: secret/data/keycloak/admin
      property: password