loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: s3
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      s3:
        endpoint: http://192.168.2.156:9000
        accessKeyId: admin
        secretAccessKey: mirecloud
        s3ForcePathStyle: true
        insecure: true

    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce

  write: { replicas: 0 }
  read: { replicas: 0 }
  backend: { replicas: 0 }

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false

  gateway:
    enabled: true
    service:
      type: ClusterIP

###############################################################################
# PROMTAIL
###############################################################################
promtail:
  enabled: true

  # 👇 1. On donne accès au dossier physique des logs d'audit à Promtail
  extraVolumes:
    - name: audit-logs
      hostPath:
        path: /var/log/kubernetes/audit
  extraVolumeMounts:
    - name: audit-logs
      mountPath: /var/log/kubernetes/audit
      readOnly: true

  config:
    clients:
      # 👇 LE VRAI NOM DU SERVICE EST "loki-stack-gateway"
      - url: http://loki-stack-gateway.monitoring.svc.cluster.local/loki/api/v1/push

    # 👇 2. On apprend à Promtail à scraper et décoder l'audit Kubernetes
    snippets:
      extraScrapeConfigs: |
        - job_name: kubernetes-audit
          static_configs:
            - targets:
                - localhost
              labels:
                job: kubernetes-audit
                __path__: /var/log/kubernetes/audit/*.log
          pipeline_stages:
            - json:
                expressions:
                  audit_user: user.username
                  audit_verb: verb
                  audit_namespace: objectRef.namespace
                  audit_resource: objectRef.resource
            - labels:
                audit_user:
                audit_verb:
                audit_namespace:
                audit_resource:
