###############################################################################
# LOKI (subchart grafana/loki)
###############################################################################
loki:
  deploymentMode: SingleBinary
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  limits_config:
    retention_period: 168h

  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce

  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0

  gateway:
    enabled: true
    service:
      type: ClusterIP

  minio:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
    grafanaAgent:
      installOperator: false

  test:
    enabled: false

###############################################################################
# PROMTAIL
###############################################################################
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-stack-gateway.monitoring.svc.cluster.local/loki/api/v1/push
