# Fichier values.yaml de ton "Wrapper" (chart parent)
open-webui:
  ollama:
    enabled: false

  extraEnvVars:
    - name: OLLAMA_BASE_URL
      value: "http://ollama.ollama.svc.cluster.local:11434"
    - name: WEBUI_AUTH
      value: "true"

  persistence:
    enabled: true
    size: "8Gi"
    storageClass: "nfs-client"