kube-prometheus-stack:
  grafana:
    enabled: true
    envFromSecret: grafana-keycloak-secret

    # --- CONFIGURATION DE LA SOURCE DE DONNÉES LOKI ---
    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack.monitoring.svc.cluster.local:3100
        version: 1
        editable: true # Permet de modifier via l'UI si besoin
        jsonData:
          maxLines: 1000

    grafana.ini:
      server:
        domain: grafana.mirecloud.com
        root_url: "https://grafana.mirecloud.com"
        serve_from_sub_path: false

      log:
        level: info
        mode: console
        format: json

      auth:
        disable_login_form: false
        oauth_auto_login: false
        log_token_exchange: true
        log_user_id: true

      auth.generic_oauth:
        enabled: true
        name: "Keycloak"
        allow_sign_up: true
        client_id: "grafana"
        client_secret: $__env{client_secret}
        scopes: "openid profile email"
        tls_skip_verify_insecure: true

        auth_url: "https://keycloak.mirecloud.com/auth/realms/mirecloud/protocol/openid-connect/auth"
        token_url: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/realms/mirecloud/protocol/openid-connect/token"
        api_url: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/realms/mirecloud/protocol/openid-connect/userinfo"

        role_attribute_path: "contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'"
        role_attribute_strict: true

    ingress:
      enabled: false

  prometheus:
    ingress:
      enabled: false
