kube-prometheus-stack:
  grafana:
    enabled: true
    envFromSecret: grafana-keycloak-secret

    grafana.ini:
      server:
        domain: grafana.mirecloud.com
        root_url: "https://grafana.mirecloud.com"

      # --- CONFIG LOGS MAXIMUM (DEBUG) ---
      log:
        level: debug # On passe de info à debug
        mode: console
        format: json

      auth:
        disable_login_form: false
        oauth_auto_login: false
        # Debugging profond de l'OIDC
        log_token_exchange: true
        log_user_id: true

      auth.generic_oauth:
        enabled: true
        name: "Keycloak"
        # On force le debug spécifique sur l'OAuth
        debug: true
        client_id: "grafana"
        client_secret: $__env{client_secret}
        scopes: "openid profile email"
        tls_skip_verify_insecure: true

        auth_url: "https://keycloak.mirecloud.com/auth/realms/mirecloud/protocol/openid\
          -connect/auth"
        token_url: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/r\
          ealms/mirecloud/protocol/openid-connect/token"
        api_url: "http://keycloak-keycloakx-http.keycloak.svc.cluster.local:80/auth/rea\
          lms/mirecloud/protocol/openid-connect/userinfo"

        role_attribute_path: "contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'"
        role_attribute_strict: true

    ingress:
      enabled: false

  prometheus:
    ingress:
      enabled: false
