# Secret pour la DB
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-es
  namespace: n8n
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-db-creds
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/n8n/db
        property: postgres-password

---
# Secret pour Redis
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-redis-es
  namespace: n8n
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-redis-creds
    creationPolicy: Owner
  data:
    - secretKey: redis-password        # ← seul changement : était "password"
      remoteRef:
        key: secret/n8n/redis
        property: password