apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "kill-curl-process"
  namespace: monitoring
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/usr/bin/curl" # La commande interdite
          matchActions:
            - action: Sigkill # ☠️ L'action immédiate : TUER LE PROCESSUS
