apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-admin-es
  namespace: pgadmin
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-admin-password # Doit correspondre au nom dans ton values.yaml
  data:
  - secretKey: password
    remoteRef:
      key: secret/pgadmin/admin
      property: password