apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-custom-ca-es
  namespace: gitlab          #  Le namespace doit exister (ou être créé par ArgoCD)
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend      # On utilise le pont global qu'on a réparé
    kind: ClusterSecretStore
  target:
    name: secret-custom-ca   #  Le nom exact attendu par ton values.yaml GitLab
    template:
      engineVersion: v2
      data:
        # On crée une clé avec une extension .crt pour que GitLab comprenne que c'est un certificat
        mirecloud-ca.crt: "{{ .ca_cert }}"
  data:
  - secretKey: ca_cert
    remoteRef:
      key: mirecloud/ca      # Chemin dans Vault
      property: tls.crt      #  IMPORTANT : On ne prend QUE la partie publique (crt), pas la clé privée !