apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-ca-es
  namespace: gitlab
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-custom-ca-secret # Le nom du secret K8s final
  data:
  # Important : La clé DOIT finir par .crt pour que GitLab la traite comme un certificat
  - secretKey: mirecloud-ca.crt
    remoteRef:
      key: secret/gitlab/runner # On réutilise l'endroit où on l'avait stocké
      property: ca_cert