apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-ca-es
  namespace: gitlab
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-custom-ca-secret # <--- Le nom exact qui manque
  data:
  - secretKey: mirecloud-ca.crt
    remoteRef:
      key: secret/gitlab/runner # On reprend là où on l'avait stocké
      property: ca_cert