apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-db-es
  namespace: gitlab
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-postgresql-password # Le nom attendu par le chart
  data:
  - secretKey: postgres-password     # La clé attendue par le chart
    remoteRef:
      key: secret/gitlab/db
      property: password