apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-oidc-es
  namespace: gitlab
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-oidc-config # Le secret que GitLab va lire
  data:
  - secretKey: provider      # La clé attendue par GitLab (souvent 'provider')
    remoteRef:
      key: secret/gitlab/oidc
      property: provider